### ISSUE TITLE
請問

### ISSUE THREAD

**Issue by linsamtw** [songyunlu/nvidia-gpu-installation-scripts#1]
請問這是在docker上才能成功嗎？

如果沒有docker是不是就會失敗？

**Comment by ChihChengLiang** [comment]
這個指令應該會幫你安裝 docker 了哦～理論上要成功

**Comment by linsamtw** [comment]
這需要安裝cuda,cudnn之類的嗎?
顯卡版本會有影響嗎?
gtx 1070 or gtx 1080等等

**Comment by songyunlu** [comment]
Hi @f496328mm 

這個 script 只有安裝 docker, nvidia-docker, 以及 nvidia gpu driver。沒有安裝 cuda 跟 cudnn。
如果你是使用 container 來跑 GPU 的程式的話，一般來說會在 container 的 image 裡裝 cuda、cudnn 等  library，而不是在 host 機器上。詳情請參考 [Nvidia-Docker Wiki](https://github.com/NVIDIA/nvidia-docker/wiki/Why%20NVIDIA%20Docker#motivation)。

那不同的顯示卡的 driver 是有差別的，這個 script 測試的 GPU 是 Nvidia Tesla K80。而安裝的 driver 有支援的顯示卡為
```
P-Series:
Tesla P100, Tesla P40, Tesla P4

K-Series:
Tesla K80, Tesla K40c, Tesla K40m, Tesla K40s, Tesla K40st, Tesla K40t, Tesla K20Xm, Tesla K20m, Tesla K20s, Tesla K20c, Tesla K10, Tesla K8

C-Class:
Tesla C2075, Tesla C2070, Tesla C2050

M-Class:
M60, M40, M6, M4, M2090, M2075, M2070, M2070-Q, M2050

X-Class:
Tesla X2070, Tesla X2090
```

至於 GeForce 系列的顯卡 (gtx 1070, gtx 1080)，則需要安裝不同的 driver。你可以在 Nvidia 的官方網站下載 [http://www.nvidia.com/Download/index.aspx](http://www.nvidia.com/Download/index.aspx)
